
title: my Book
  
execute:
  # Force re-execution of notebooks on each build.
  # See https://jupyterbook.org/content/execute.html
  execute_notebooks: force
  timeout: -1  # Disable timeouts for executing notebooks cells
  allow_errors: true  # Allow errors in notebook cells
