name: book-env
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter-book<2.0
  - python<3.14 # som pyvista incompatibility issues with python 3.14
  - pyvista
  - jupyter
  - sphinx-codeautolink
  - pyparsing
  - trame
  - vtk
  - trame-vtk<2.10.3
  - trame-vuetify
  - nest-asyncio2
