name: book-env
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter-book<2.0
  - python<3.14  # som pyvista incompatibility issues with python 3.14
  - fenics-dolfinx
  - pyvista
  - jupyter
  - pyparsing
  - trame
  - vtk
  - trame-vtk
  - trame-vuetify
  - nest-asyncio2